package com.example.weatherapp.model.enums;

import java.util.Arrays;

public enum CityName {
    Adana,
    Adıyaman,
    Afyonkarahisar,
    Ağrı,
    Amasya,
    Ankara,
    Antalya,
    Artvin,
    Aydın,
    Balıkesir,
    Bilecik,
    Bingöl,
    Bitlis,
    Bolu,
    Burdur,
    Bursa,
    Çanakkale,
    Çankırı,
    Çorum,
    Denizli,
    Diyarbakır,
    Edirne,
    Elazığ,
    Erzincan,
    Erzurum,
    Eskişehir,
    Gaziantep,
    Giresun,
    Gümüşhane,
    Hakkari,
    Hatay,
    Isparta,
    Mersin,
    İstanbul,
    İzmir,
    Kars,
    Kastamonu,
    Kayseri,
    Kırklareli,
    Kırşehir,
    Kocaeli,
    Konya,
    Kütahya,
    Malatya,
    Manisa,
    Kahramanmaraş,
    Mardin,
    Muğla,
    Muş,
    Nevşehir,
    Niğde,
    Ordu,
    Rize,
    Sakarya,
    Samsun,
    Siirt,
    Sinop,
    Sivas,
    Tekirdağ,
    Tokat,
    Trabzon,
    Tunceli,
    Şanlıurfa,
    Uşak,
    Van,
    Yozgat,
    Zonguldak,
    Aksaray,
    Bayburt,
    Karaman,
    Kırıkkale,
    Batman,
    Şırnak,
    Bartın,
    Ardahan,
    Iğdır,
    Yalova,
    Karabük,
    Kilis,
    Osmaniye,
    Düzce;

    public static CityName fromStringtoEnum(String cityName){
        if (cityName == null || cityName.isBlank()) {
            throw new IllegalArgumentException("City name cannot be null or blank");
        }
        String normalizedInput = cityName.trim();
        return Arrays.stream(CityName.values())
                .filter(c -> c.name().equalsIgnoreCase(normalizedInput))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Invalid city name: " + cityName));
    }
}
